15-cafewang/back-end

- src/main/java/com/sparta/backend/controller/BoardCommentController.java
- src/main/java/com/sparta/backend/controller/BoardCommentLikesController.java
- src/main/java/com/sparta/backend/controller/BoardLikesController.java
- src/main/java/com/sparta/backend/domain/BoardComment.java
- src/main/java/com/sparta/backend/domain/BoardCommentLikes.java
- src/main/java/com/sparta/backend/domain/BoardLikes.java
- src/main/java/com/sparta/backend/dto/request/board/GetBoardCommentResponseDto.java
- src/main/java/com/sparta/backend/dto/request/board/PostBoardCommentRequestDto.java
- src/main/java/com/sparta/backend/repository/BoardCommentLikesRepository.java
- src/main/java/com/sparta/backend/repository/BoardCommentRepository.java
- src/main/java/com/sparta/backend/repository/BoardLikesRepository.java
- src/main/java/com/sparta/backend/service/BoardCommentLikesService.java
- src/main/java/com/sparta/backend/service/BoardCommentService.java
- src/main/java/com/sparta/backend/service/BoardLikesService.java
- 게시물 댓글 CRUD 기능 추가
- 게시물 좋아요/취소 기능 추가
새로운 깃 관리 정책으로 인해 이전의 커밋 내용을 한번에 PR 합니다.
> [기능추가] 게시물 댓글, 좋아요 관련 기능 추가

- src/main/java/com/sparta/backend/controller/BoardCommentController.java
- src/main/java/com/sparta/backend/domain/BoardComment.java
- src/main/java/com/sparta/backend/dto/request/board/PutBoardCommentRequestDto.java
- src/main/java/com/sparta/backend/service/BoardCommentService.java
> [기능추가] 댓글 수정 기능 추가

- src/main/java/com/sparta/backend/BackEndApplication.java
- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/controller/MainpageController.java
- src/main/java/com/sparta/backend/dto/queryInterface/PopularRecipeInterface.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeListResponseDto.java
- src/main/java/com/sparta/backend/repository/RecipeLikesRepository.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/Recipe/RecipeService.java
- 일간, 주간, 월간 좋아요 가장 많이 등록된 top3 레시피 정보 출력하는 sql, jpql 작성
- native query, jpql을 원하는 칼럼만 추출하여 개별 타입으로 받는 interface 작성.
파이링~~~~
> [기능추가] 인기레시피 추천(일간, 주간, 월간)

- src/main/java/com/sparta/backend/controller/UserinfoController.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetRecipeListResponseDto.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetUserinfoResponseDto.java
- src/main/java/com/sparta/backend/repository/FollowRepository.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/UserinfoService.java
- src/main/java/com/sparta/backend/service/UserinfoServiceImpl.java
파라미터로 받아온 닉네임이 로그인한 닉네임과 일치시 자신의 유저페이지 조회
다를경우 타 사용자의 유저페이지 조회
> [기능추가] 유저페이지 조회, 내가 쓴 레시피 목록 조회 기능 추가

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/controller/BoardController.java
- src/main/java/com/sparta/backend/repository/BoardRepository.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 키워드를 입력하여 게시물의 검색 결과를 확인
- 제목 또는 내용에 키워드가 포함되어있을 경우 검색 결과에 나타남
화이팅!
> [기능추가] 게시물 검색 기능 추가

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
update: 댓글dto에 이미지도 함께 응답
사소한 기능 추가입니다. 
이걸로 api mvp기능은 마무리 될 것 같습니다!
> [업데이트] 댓글dto에 이미지도 함께 응답

- .gitignore
- src/main/java/com/sparta/backend/controller/UserinfoController.java
- src/main/java/com/sparta/backend/domain/Recipe/RecipeImage.java
- src/main/java/com/sparta/backend/domain/Tag.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetBoardListResponseDto.java
- src/main/java/com/sparta/backend/repository/BoardRepository.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/UserinfoService.java
- src/main/java/com/sparta/backend/service/UserinfoServiceImpl.java
- 내가쓴 게시글 목록 조회 기능
- 내가 좋아요한 레시피 목록 조회 기능
- 내가 좋아요한 게시글 목록 조회 기능
- 연관관계 객체 ToString에서 제외
> [기능추가] 좋아요한 레시피, 게시글 목록 조회 기능 추가

- src/main/java/com/sparta/backend/service/BoardCommentService.java
- src/main/java/com/sparta/backend/service/BoardService.java
- page index가 0에서 시작하는 것이 아닌 1에서 시작하도록 수정
> [업데이트] 페이지 시작 index 수정(게시물 조회, 게시물 검색, 댓글 조회)

- src/main/java/com/sparta/backend/controller/UserinfoController.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetFollowerListResponseDto.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetFollowingListResponseDto.java
- src/main/java/com/sparta/backend/repository/FollowRepository.java
- src/main/java/com/sparta/backend/service/UserinfoService.java
- src/main/java/com/sparta/backend/service/UserinfoServiceImpl.java
- 팔로워 목록 조회
- 팔로우 목록 조회
- 기타 오타 수정
> [기능추가] 팔로잉, 팔로우 목록 조회 기능 추가

- src/main/java/com/sparta/backend/dto/response/board/GetBoardResponseDto.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 조회 responseDto에 이미지가 없을 경우 null로 response 하도록 수정
- 게시물 작성 시 이미지를 첨부 안 했을 경우(제목과 내용만 입력했을 경우)에도 Insert 하도록 로직 수정
- 게시물 상세 조회 시 이미지가 없을 경우 길이가 0인 List로 response 하도록 수정
> [업데이트] 이미지 없는 게시물 처리 시 사용되는 로직 수정

- src/main/java/com/sparta/backend/controller/UserController.java
- src/main/java/com/sparta/backend/service/UserService.java
- 이메일 중복 체크시 형식 체크
- 닉네임 중복 체크시 형식 체크
- userId 대신 userDetails 쓰도록 리펙토링
> [기능추가] 이메일, 닉네임 형식 검사 로직 추가

- src/main/java/com/sparta/backend/controller/UserController.java
- src/main/java/com/sparta/backend/service/KakaoUserService.java
- src/main/java/com/sparta/backend/service/UserService.java
- 카카오 로그인 응답 데이터 변경
- 기본 프로필 사진 추가
- 카카오 redirect uri 변경
> [기능수정] 카카오 응답 데이터, uri 변경

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/dto/request/board/PutBoardRequestDto.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 게시물 수정 API 로직 수정
- 게시물 삭제 API에서 반복적으로 Delete하는 로직 수정
> [업데이트] 게시물 수정/삭제 API 로직 수정

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/domain/BaseEntity.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeDetailResponsetDto.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeListResponseDto.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/Recipe/RecipeCommentService.java
- src/main/java/com/sparta/backend/service/ReviewServiceImpl.java
프론트에서 regdate을 regDate으로 통일해달라는 요청에 맞추어 업데이트하였습니다.
regdate을 사용하는 관련된 기능들이 많아서 다 테스트는 해보았습니다.
> [변수명 변경] regdate -> regDate

- src/main/java/com/sparta/backend/domain/User.java
- src/main/java/com/sparta/backend/validator/UserValidator.java
- src/test/java/com/sparta/backend/domain/user/UserTest.java
- src/test/java/com/sparta/backend/validator/UserValidatorTest.java
- validator 생성
- 이메일 검증
- 비밀번호 검증
- 닉네임 검증
- 엔티티 객체 생성 테스트
> [테스트] User 엔티티 테스트 추가

- src/main/java/com/sparta/backend/dto/response/recipes/RecipeDetailResponsetDto.java
- src/main/java/com/sparta/backend/service/Recipe/RecipeService.java
레시피 상세조회 응답메시지에 price를 추가하였습니다.
> [기능수정] 레시피 상세조회 price 추가

- src/main/java/com/sparta/backend/repository/BoardRepository.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 쿼리스트링의 sortBy에 'likeCount'를 입력 시 인기순으로 게시물 조회
함수명이 좀 깁니다..ㅎㅎ
> [업데이트] 게시물 전체 조회, 게시물 검색 로직 수정

- src/main/java/com/sparta/backend/domain/Board.java
- src/main/java/com/sparta/backend/dto/request/board/PostBoardRequestDto.java
- src/main/java/com/sparta/backend/validator/BoardValidator.java
- src/test/java/com/sparta/backend/domain/BoardTest.java
> [테스트코드 ]Board 엔티티 테스트코드 추가

- src/main/java/com/sparta/backend/controller/MainpageController.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- 기능수정: 페이지로 응답 -> top4만 응답
- 버그수정: entity 칼럼명 바꿀때 sql 테이블명은 안 바뀌는 현상발생. sql의 테이블도 바꿈
> [기능수정] 메인페이지 레시피 최근조회

- src/main/java/com/sparta/backend/controller/UserController.java
- src/main/java/com/sparta/backend/domain/User.java
- src/main/java/com/sparta/backend/dto/request/user/UpdateNicknameRequestDto.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetUserinfoResponseDto.java
- src/main/java/com/sparta/backend/service/UserService.java
- src/main/java/com/sparta/backend/service/UserinfoServiceImpl.java
- 기존에 있던 닉네임 + 이미지 수정 기능이
이미지 파일 업로드를 안하게되면 에러가 나서
두 가지를 분리했습니다
- likeStatus 타입을 String -> boolean 으로 변경
> [기능추가] 닉네임 수정 기능 추가

- src/main/java/com/sparta/backend/domain/BoardComment.java
- src/main/java/com/sparta/backend/validator/BoardCommentValidator.java
- src/test/java/com/sparta/backend/domain/BoardCommentTest.java
- BoardComment 엔티티를 생성할 때 나타날 수 있는 에러사항을 테스트하는 코드 추가
> [테스트] BoardComment 엔티티 테스트코드 추가

- src/main/java/com/sparta/backend/dto/response/recipes/RecipeDetailResponsetDto.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
> [기능수정] 레시피 상세조회 시 프로필 이미지 추가 

- src/main/java/com/sparta/backend/domain/BoardImage.java
- src/main/java/com/sparta/backend/validator/BoardImageValidator.java
- src/test/java/com/sparta/backend/domain/BoardImageTest.java
- BoardImage 엔티티 validation 테스트코드 추가
어제 커밋만 해둔 것들 오늘 push해서 PR 날립니다
오늘 다들 수고 많으셨습니다
> [테스트] BoardImage 엔티티 테스트코드 추가

- src/main/java/com/sparta/backend/repository/RecipeImageRepository.java
- src/main/java/com/sparta/backend/repository/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- 수정하면서 사진 추가시 총 기존사진+추가사진이 5장이 넘을 경우 예외처리
- url만 알면 다른 게시물의 사진도 삭제할 수 있던 문제 예외처리
> [예외처리] 레시피 수정 예외처리

- src/main/java/com/sparta/backend/controller/BoardController.java
- src/main/java/com/sparta/backend/dto/request/board/PutBoardRequestDto.java
- src/main/java/com/sparta/backend/repository/BoardImageRepository.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 프론트에서 삭제할 이미지 URL을 받아 삭제할 수 있도록 로직 수정
- 가독성을 위해 일부 로직을 메소드로 묶어 정리
> [기능수정] 게시물 수정 로직 변경

- src/test/java/com/sparta/backend/integration/RecipeIntegrationTest.java
깃허브 액션 배포자동화를 위해 테스트실패케이스 주석처리하였습니다.
> [테스트수정] 실패 테스트케이스 주석처리

- src/test/java/com/sparta/backend/integration/RecipeIntegrationTest.java
> fix: 통합테스트 전체주석

- src/main/java/com/sparta/backend/dto/request/recipes/PutRecipeRequestDto.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- src/test/java/com/sparta/backend/integration/RecipeIntegrationTest.java
- form-data로 오는 키값이 null일 때 예외처리
- 현재 실행되지 않는 테스트코드 주석처리
> [예외처리]레시피 수정 dto null 예외

- src/main/java/com/sparta/backend/controller/FollowController.java
- src/main/java/com/sparta/backend/dto/request/user/SignupRequestDto.java
- src/main/java/com/sparta/backend/service/FollowService.java
- 팔로우 중복 예외 처리
- 자기 자신 팔로우 예외 처리
- 기존 userId로 로그인 한 회원을 조회해오는 쿼리가 나갔던 점 userDetails로 처리
- dto에 기본 생성자 추가
> [기능수정] 팔로우 기능 로직 변경

- src/main/java/com/sparta/backend/controller/BoardController.java
- src/main/java/com/sparta/backend/service/BoardService.java
- 새 이미지를 올리는 과정에서 exception이 발생하면 S3에서 이미지들을 지우고 exception을 controller에 전달
> [기능수정] 게시물 수정 API 예외처리 수정

- src/main/java/com/sparta/backend/dto/request/board/GetBoardCommentResponseDto.java
- src/main/java/com/sparta/backend/service/BoardCommentService.java
- 게시물 댓글 전체 조회 시 수정일도 나타나도록 수정
- 로그인 확인, 작성자 확인 함수 생성 후 적용
> [기능수정] 게시물 댓글 전체 조회 response 수정

- src/main/java/com/sparta/backend/controller/UserController.java
- src/main/java/com/sparta/backend/controller/UserinfoController.java
> [기능추가] 로그인 체크 기능 추가

- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- 추천로직 쿼리문 보완하였습니다. 계속 수정해나가야 할 것 같습니다.(현재 완벽하지 않음)
- 댓글 응답 메시지에 레시피id도 넣어두었습니다.
> [기능수정] 추천로직 보완, 댓글응답메시지 추가

- src/main/java/com/sparta/backend/controller/MainpageController.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
> [기능수정 ]최근레시피 조회 4개->3개

- src/main/java/com/sparta/backend/config/WebConfig.java
- src/main/java/com/sparta/backend/controller/RecipeCommentController.java
- src/main/java/com/sparta/backend/domain/recipe/Recipe.java
- src/main/java/com/sparta/backend/domain/recipe/RecipeComment.java
- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
- src/main/java/com/sparta/backend/service/KakaoUserService.java
- src/main/java/com/sparta/backend/service/recipe/RecipeCommentService.java
- cascade옵션 설정으로, 통계처리 레시피와 레시피 삭제 레시피 함께 삭제
- 댓글 등록/수정 응답 메시지 수정
> [오류수정] 레시피 삭제, 댓글수정 수정

- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
> [오작동 수정] 댓글 프로필 이미지 수정

- src/main/java/com/sparta/backend/controller/BoardCommentController.java
- src/main/java/com/sparta/backend/domain/BoardComment.java
- src/main/java/com/sparta/backend/dto/response/board/GetBoardCommentResponseDto.java
- src/main/java/com/sparta/backend/service/BoardCommentService.java
- 댓글 작성/수정 API에서 response를 댓글작성/수정 시 입력했던 데이터로 return하도록 로직 수정
> [기능수정] 게시물 댓글 작성/수정 API response 수정

- src/main/java/com/sparta/backend/repository/recipe/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- 레시피 추천 시 레시피와 함께, 어떤 태그를 기반으로 뽑았는지 태그도 함께 응답함.
- foundRecipeId == null 인 경우(즉, 내가 검색한 태그명으로 나를 포함한 누구도 상세조회, 좋아요를 하지 않은 경우) 랜덤으로 레시피를 뽑아주도록 처리
> [기능보완] 레시피 추천로직 보완

- src/main/java/com/sparta/backend/dto/response/recipes/RecipeCommentResponseDto.java
> [기능수정] 요청응답메시지 수정

- src/main/java/com/sparta/backend/controller/user/FollowController.java
- src/main/java/com/sparta/backend/controller/user/UserController.java
- src/main/java/com/sparta/backend/controller/user/UserinfoController.java
- src/main/java/com/sparta/backend/exception/GlobalControllerAdvice.java
- src/main/java/com/sparta/backend/service/user/UserService.java
> [기능수정] 응답 메시지 수정

- src/main/java/com/sparta/backend/controller/MainpageController.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
> [업데이트] recipe 추천 응답형식 list로 변환

- src/main/java/com/sparta/backend/controller/recipe/RecipeController.java
- src/main/java/com/sparta/backend/domain/recipe/Recipe.java
- src/main/java/com/sparta/backend/dto/queryInterface/PopularRecipeInterface.java
- src/main/java/com/sparta/backend/dto/request/recipe/PostRecipeRequestDto.java
- src/main/java/com/sparta/backend/dto/request/recipe/PutRecipeRequestDto.java
- src/main/java/com/sparta/backend/dto/response/recipe/RecipeDetailResponsetDto.java
- src/main/java/com/sparta/backend/dto/response/recipe/RecipeListResponseDto.java
- src/main/java/com/sparta/backend/dto/response/recipe/RecipeRecommendResponseDto.java
- src/main/java/com/sparta/backend/dto/response/userinfo/GetRecipeListResponseDto.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeRepository.java
- src/main/java/com/sparta/backend/service/recipe/RecipeService.java
- src/main/java/com/sparta/backend/validator/PostRecipeRequestDtoValidator.java
- src/main/java/com/sparta/backend/validator/RecipeValidator.java
- src/test/java/com/sparta/backend/domain/recipe/RecipeTest.java
- src/test/java/com/sparta/backend/integration/RecipeIntegrationTest.java
- src/test/java/com/sparta/backend/mvc/RecipeControllerTest.java
Integer price -> String lcoation으로 수정하였습니다.
> [엔티티 속성변경] price -> location

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/domain/recipe/RecipeImage.java
- src/main/java/com/sparta/backend/exception/GlobalControllerAdvice.java
- src/main/java/com/sparta/backend/exception/ImageNameTooLongException.java
- src/main/java/com/sparta/backend/validator/RecipeValidator.java
- src/test/java/com/sparta/backend/domain/recipe/RecipeCommentTest.java
- src/test/java/com/sparta/backend/domain/recipe/RecipeTest.java
장소길이 제한, 사진 제목길이 제한, 디비 길이제한 조정
> [기능수정] 길이제한 검증

- src/main/java/com/sparta/backend/service/user/KakaoUserService.java
> [기능수정] 카카오 닉네임 로직 수정

- src/main/java/com/sparta/backend/controller/RankingController.java
- src/main/java/com/sparta/backend/dto/response/user/GetKingUserInfoLastWeekResponseDto.java
- src/main/java/com/sparta/backend/dto/response/user/GetKingsLastWeekResponseDto.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeCommentRepository.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeLikesRepository.java
- src/main/java/com/sparta/backend/repository/recipe/RecipeRepository.java
- src/main/java/com/sparta/backend/repository/user/UserRepository.java
- src/main/java/com/sparta/backend/service/RankingService.java
- 저번 주 좋아요/팔로우/게시물/댓글 왕 조회 기능 추가
궁금한거 생기면 댓글 남겨주세요!
> [기능추가] 저번주 좋아요/팔로우/게시물/댓글 왕 조회 기능 추가

- src/main/java/com/sparta/backend/controller/RankingController.java
- src/main/java/com/sparta/backend/service/RankingService.java
- Dto 하나를 List에 담아 return하고 있었지만 List를 뺀 Dto를 return하도록 변경
> [기능수정] 저번주 왕 목록 response 형식 수정

- src/main/java/com/sparta/backend/controller/MainpageController.java
- src/main/java/com/sparta/backend/controller/cafe/CafeController.java
- src/main/java/com/sparta/backend/controller/user/UserinfoController.java
- src/main/java/com/sparta/backend/repository/cafe/CafeRepository.java
- src/main/java/com/sparta/backend/service/cafe/CafeCommentService.java
- src/main/java/com/sparta/backend/service/cafe/CafeService.java
- src/main/java/com/sparta/backend/service/user/UserinfoService.java
- src/main/java/com/sparta/backend/service/user/UserinfoServiceImpl.java
- src/test/java/com/sparta/backend/domain/cafe/RecipeCommentTest.java
- src/test/java/com/sparta/backend/domain/cafe/RecipeTest.java
- src/test/java/com/sparta/backend/integration/RecipeIntegrationTest.java
- src/test/java/com/sparta/backend/mvc/CafeControllerTest.java
주석과 응답메시지 중 '레시피'라는 단어를 '카페'로 변경하였습니다.
> [주석, 응답메시지 변경] 레시피 -> 카페 변경

- src/main/java/com/sparta/backend/controller/user/UserController.java
- src/main/java/com/sparta/backend/service/user/UserService.java
> [기능수정] 로그인시 응답 메시지 변경

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/controller/cafe/CafeCommentController.java
- src/main/java/com/sparta/backend/domain/cafe/CafeReply.java
- src/main/java/com/sparta/backend/domain/cafe/CafeReplyLike.java
- src/main/java/com/sparta/backend/dto/request/cafe/CafePostReplyRequestDto.java
- src/main/java/com/sparta/backend/dto/response/cafe/CafeReplyResponseDto.java
- src/main/java/com/sparta/backend/repository/cafe/CafeReplyLikeRepository.java
- src/main/java/com/sparta/backend/repository/cafe/CafeReplyRepository.java
- src/main/java/com/sparta/backend/service/cafe/CafeReplyService.java
-대댓글 입력하기 기능 추가하였습니다
-대댓글 조회, 수정, 삭제, 좋아요 기능은 아직입니다.
> [기능추가] 대댓글 입력

- src/main/java/com/sparta/backend/repository/cafe/CafeRepository.java
- src/main/java/com/sparta/backend/service/cafe/CafeService.java
- src/main/java/com/sparta/backend/validator/CafeCommentValidator.java
#102 의 나영님 코멘트 요청에 따라 닉네임검색기능 추가하였습니다.
- 버그수정: 길이제한,
- 기능수정: 장소검색, 닉네임검색 쿼리 추가
> [기능수정] 입력길이제한, 검색기능수정

- src/main/java/com/sparta/backend/repository/user/UserRepository.java
- src/main/java/com/sparta/backend/service/user/RankingService.java
- 저번주 좋아요왕, 팔로우왕을 결정하는 SQL에 문제가 있는 것 같아 수정
- 저번주 좋아요왕, 팔로우왕 SQL을 수정하면서 게시물왕, 댓글왕 SQL 형식 맞춰줌
> [기능수정] 저번주 좋아요/팔로우/게시물/댓글 왕 조회 SQL 수정

- src/main/java/com/sparta/backend/controller/cafe/CafeCommentController.java
- src/main/java/com/sparta/backend/controller/cafe/CafeController.java
- src/main/java/com/sparta/backend/controller/user/UserController.java
- src/main/java/com/sparta/backend/domain/user/User.java
- src/main/java/com/sparta/backend/domain/user/UserRole.java
- src/main/java/com/sparta/backend/dto/request/user/DeleteUserRequestDto.java
- src/main/java/com/sparta/backend/service/board/BoardCommentService.java
- src/main/java/com/sparta/backend/service/board/BoardService.java
- src/main/java/com/sparta/backend/service/user/UserService.java
- 어드민에게 게시글 수정/삭제 권한 부여
- 회원 탈퇴시 이메일, 닉네임, 이미지, 상태값 변경
> [기능수정] 회원 탈퇴기능, 어드민 권한 수정

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/domain/cafe/Cafe.java
- src/main/java/com/sparta/backend/dto/response/cafe/CafeListResponseDto.java
- src/main/java/com/sparta/backend/service/cafe/CafeService.java
- cafe 등록 시 이미지 여러장 일 경우 첫번째 사진을 resize해서 섬네일로 등록합니다.
- 섬네일 사진은 s3서버의 thumNail 폴더에 저장합니다.
- cafe리스트 조회 응답 시, image란 키값으로 섬네일을 리턴합니다.
- Cafe 엔티티에 thumbNailImage 속성 추가하였습니다.
> [기능개선] 섬네일 기능 추가

- src/main/java/com/sparta/backend/awsS3/S3Uploader.java
- src/main/java/com/sparta/backend/util/NullThumbNailChecker.java
- 썸네일이 회전되는 현상 해결
- 200 * 200 -> 원본 이미지 비율 로 수정
> [버그수정] 원본 이미지 비율에 맞춰 썸네일 생성

- src/main/java/com/sparta/backend/dto/response/cafe/CafeListResponseDto.java
- src/main/java/com/sparta/backend/dto/response/cafe/CafeRecommendResponseDto.java
- 왕게시물 상태 보여주는 응답로직 버그 수정
- 추천게시물 섬네일 버그수정
> [버그수정]왕게시물 왕관 수정, 추천게시물 섬네일 수정

- src/main/java/com/sparta/backend/dto/response/userinfo/GetCafeListResponseDto.java
- src/main/java/com/sparta/backend/service/cafe/CafeService.java
- 버그수정: 카페 디테일페이지에 왕관표시
- 기능추가: 사용자 정보 페이지에 섬네일 적용
> [기능수정] 사용자정보페이지에 섬네일 적용
